import enum
from datetime import datetime, timezone

from sqlalchemy import DateTime, Enum, Float, ForeignKey, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class MatchStatus(str, enum.Enum):
    suggested = "suggested"  # generated by engine
    shortlisted = "shortlisted"  # founder shortlisted
    invited = "invited"  # founder invited the developer
    accepted = "accepted"  # developer accepted -> becomes an engagement
    declined = "declined"  # developer declined
    rejected = "rejected"  # founder rejected


class Match(Base):
    """A scored project<->developer pairing produced by the matching engine."""

    __tablename__ = "matches"
    __table_args__ = (UniqueConstraint("project_id", "developer_id", name="uq_project_developer"),)

    id: Mapped[int] = mapped_column(primary_key=True)
    project_id: Mapped[int] = mapped_column(
        ForeignKey("projects.id", ondelete="CASCADE"), index=True
    )
    developer_id: Mapped[int] = mapped_column(
        ForeignKey("developer_profiles.id", ondelete="CASCADE"), index=True
    )

    # Overall score (0-100) and the component breakdown for transparency.
    score: Mapped[float] = mapped_column(Float, default=0.0, index=True)
    skill_score: Mapped[float] = mapped_column(Float, default=0.0)
    experience_score: Mapped[float] = mapped_column(Float, default=0.0)
    availability_score: Mapped[float] = mapped_column(Float, default=0.0)
    reputation_score: Mapped[float] = mapped_column(Float, default=0.0)
    fairness_score: Mapped[float] = mapped_column(Float, default=0.0)
    explanation: Mapped[str] = mapped_column(Text, default="")

    status: Mapped[MatchStatus] = mapped_column(
        Enum(MatchStatus), default=MatchStatus.suggested, index=True
    )

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=utcnow)

    project: Mapped["Project"] = relationship(back_populates="matches")  # noqa: F821
    developer: Mapped["DeveloperProfile"] = relationship()  # noqa: F821
